name: Create Release

on:
  push:
    branches:
      - main # Adjust this to the branch where you want to detect the commits

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for "RELEASE" in commit message and extract version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -o 'RELEASE v[0-9]\+\.[0-9]\+')
          if [[ ! -z "$VERSION" ]]; then
            VERSION=${VERSION#*v}
          else
            VERSION=${{ github.sha }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create .tar.gz of the source files
        if: env.VERSION != ''
        run: |
          mkdir temp
          rsync -av --progress . temp --exclude temp --exclude .git
          tar -cvzf hello_brew.tar.gz -C temp .
          SHA256=$(sha256sum hello_brew.tar.gz | awk '{ print $1 }')
          echo "SHA256=$SHA256" >> $GITHUB_ENV
          rm -rf temp

      - name: Create Release
        if: env.VERSION != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: |
            Release of version ${{ env.VERSION }}
            SHA256 checksum: ${{ env.SHA256 }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: env.VERSION != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hello_brew.tar.gz
          asset_name: hello_brew.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout homebrew-tap repository
        uses: actions/checkout@v2
        with:
          repository: jackinf/homebrew-tap
          ref: main
          token: ${{ secrets.TAPPY }} # Make sure this token has necessary permissions

      - name: Update Formula
        run: |
          VERSION=${{ env.VERSION }}
          URL="https://github.com/jackinf/HelloBrew2/releases/download/v${VERSION}/hello_brew.tar.gz"
          sed -i "s|url \".*\"|url \"$URL\"|" ./Formula/hello-brew.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" ./Formula/hello-brew.rb

      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./Formula/hello-brew.rb
          git commit -m "Update hello-brew formula to version ${{ env.VERSION }}"
          git push origin main
