name: Create Release

on:
  push:
    branches:
      - main # Adjust this to the branch where you want to detect the commits

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for "RELEASE" in commit message and extract version
        run: |
          VERSION=$(git log -1 --pretty=%B | grep -o 'RELEASE v[0-9]\+\.[0-9]\+')
          if [[ ! -z "$VERSION" ]]; then
            VERSION=${VERSION#*v}
          else
            VERSION=${{ github.sha }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create .tar.gz of the source files
        if: env.VERSION != ''
        run: tar -cvzf source_code_v${{ env.VERSION }}.tar.gz . --exclude='.git'

      - name: Create Release
        if: env.VERSION != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: Auto release for version v${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        if: env.VERSION != ''
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./source_code_v${{ env.VERSION }}.tar.gz
          asset_name: source_code_v${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Formula
        if: env.VERSION != ''
        run: |
          VERSION=${{ env.VERSION }}
          SHA256=$(sha256sum source_code_v${VERSION}.tar.gz | awk '{ print $1 }')
          URL="https://github.com/jackinf/HelloBrew2/releases/download/${VERSION}/hello-brew.tar.gz"
          sed -i "s|url \".*\"|url \"$URL\"|" ./path/to/Formula/hello-brew.rb
          sed -i "s|sha256 \".*\"|sha256 \"$SHA256\"|" ./path/to/Formula/hello-brew.rb
